openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3001
    description: Dev Server
paths:
  /bedrijven:
    get:
      responses:
        '200':
          description: OK
