openapi: '3.1.1'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []


info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3001
    description: Dev Server
paths:
  /bedrijven:
    get:
      responses:
        '200':
          description: OK
